### ISSUE TITLE
House Keeping

### ISSUE THREAD

**Issue by jacobtomlinson** [met-office-lab/data-stream#8]
Ingesting data will cause our storage space to fill up (50GB per day).

We need to implement some form of house keeping to remove old data. Should this be done by the same script that does the ingestion or by a separate one?

@RPrudden @niallrobinson

**Comment by RPrudden** [comment]
Could they just get deleted as soon as the script posts them to the SNS?

**Comment by jacobtomlinson** [comment]
Do you mean once they have been converted into images?

**Comment by jacobtomlinson** [comment]
After discussion with @niallrobinson the housekeeping should be a separate microservice.
